#!/usr/bin/env php

<?php


use Framework\Console\Kernel;
use Framework\Console\KernelInterface;

require_once __DIR__."/vendor/autoload.php";

$container = require "./bootstrap/app.php";

$kernel = $container->get(
    KernelInterface::class, 
    Kernel::class
);

$status = $kernel->handle();

exit($status);